### ISSUE TITLE
Missing serialize REPR function for REPR Decoder (Rakudo::Internals::VMBackedDecoder)

### ISSUE THREAD

**Issue by MARTIMM** [bduggan/p6-log-async#14]
Hi Brian,
I saw, using the latest perl6 version, a lot of the tests in this module are failing (tests 08-\*,09-\*). The all fail because of the helper program `command-line-test.pl` which shows the error `Missing serialize REPR function for REPR Decoder (Rakudo::Internals::VMBackedDecoder)`. without any linenumber. I couldn't put my finger on it but I suspect it is somewhere in the first `send-to()` method called from `new()` which calls it without arguments but `$*OUT`. This is because when I inhibit that call in new(), these tests will run fine (although other tests will now fail).

The version I am using now is Rakudo version 2017.05-382-gccfa5e5 built on MoarVM version 2017.05-71-gad6ab26 implementing Perl 6.c.

Regards,
Marcel

**Comment by MARTIMM** [comment]
I've created a pull request for some other issue which triggered a test on travis-ci. There you can see the problems shown above.

**Comment by bduggan** [comment]
Thanks, Marcel.

I'll take a look.  In the mean time I've changed the travis config to just use the latest stable release (2017.05) where the tests seem to pass. (#16)

**Comment by MARTIMM** [comment]
For what is worth, a discussion I had yesterday. I am still pondering over it but don't understand it fully (last questions weren't answered);

```
?[14:36] ?<?MARTIMM?>? what can cause 'Missing serialize REPR function for REPR Decoder (Rakudo::Internals::VMBackedDecoder)'. it is thrown without a linenumber. It think while parsing but I am not sure.
?[14:40] ?<?jnthn?>? Trying to serialize an I/O handle, most probably.
?[14:41] ?<?jnthn?>? So, most probably something happening in a BEGIN or constant or similar
?[14:41] ?<?MARTIMM?>? jnthn: That might be possible. It pops up in Log::Async and there is a lot of I/O and some phasers
?[14:43] ?<?jnthn?>? It's possible that in the past we silently allowed I/O handles to be serialized, on the understanding that they'd only explode if you ever tried to use them in the future
?[14:43] ?<?jnthn?>? If this is a regression, then we probably would want to go back to doing that
?[14:48] ?<?MARTIMM?>? jnthn: I'm afraid I don't understand this. I understood that it is serialized by default to utf-8, does it explode when wrong characters are sent?
?[14:49] ?<?jnthn?>? Ah, I was talking about the serialization that happens when a module is compiled
?[14:49] ?<?jnthn?>? We have to preserve stuff that comes to exist at BEGIN time
?[14:50] ?<?jnthn?>? It sounds like an I/O handle is ending up in that set of things, probably unintentionally
?[14:51] ?<?MARTIMM?>? jnthn: ok. aren't the handles closed then. could  close them and reopen in the BEGIN phase?
?[14:52] ?<?MARTIMM?>? jnthn: in a new() the handle $*OUT is used from an INIT phase
```

**Comment by bduggan** [comment]
I'm now avoiding storing $*OUT during INIT, and tests are passing, so I'm closing this issue.

**Comment by MARTIMM** [comment]
Thanks very much for your work
Marcel
