### ISSUE TITLE
Flapper when testing

### ISSUE THREAD

**Issue by JJ** [bduggan/p6-log-async#28]
This has happened only once, but still https://travis-ci.org/JJ/p6-algorithm-evolutionary-simple/builds/512645784
Might be some temporary thing, but I guessed it was better to report.

**Comment by bduggan** [comment]
Thanks -- yes, it looks like the [test](https://github.com/bduggan/p6-log-async/blob/master/t/03-log.t#L15) should be improved to not rely on the thread sending the message in 0.1 seconds.
