### ISSUE TITLE
Cannot flush handle

### ISSUE THREAD

**Issue by gdonald** [bduggan/p6-log-async#29]
Log::Async fails to install on Travis sometimes.  I'm seeing several messages like this being emitted when I run the tests locally:

`Cannot flush handle: Failed to flush filehandle: Operation not supported`

I tried wrapping one of the `trace` calls with `output-is` from `Test::Output`, but it did not help.  Not sure what else to try.

**Comment by bduggan** [comment]
Hmm -- perhaps run the test with `perl6 --ll-exception`?  Which filesystem/OS is it?

**Comment by gdonald** [comment]
Today Travis installs Log::Async with no issues, not sure why it was failing before.  Closing.
