### ISSUE TITLE
error if main program doesn't use Log::Async, but uses another module that does

### ISSUE THREAD

**Issue by CurtTilmes** [bduggan/p6-log-async#8]
```
$ cat TestModule.pm6
use Log::Async;
$ cat test.pl
use TestModule;
$ perl6 -I. test.pl
===SORRY!===
No such method 'done' for invocant of type 'Any'
```

**Comment by CurtTilmes** [comment]
BTW, even though the docs say and END block only runs once, if you include two modules, that each use Log::Async, the END block gets run once for each of them.

**Comment by CurtTilmes** [comment]
Okay, sometimes it runs the Log::Async END block twice sometimes it doesn't...

**Comment by CurtTilmes** [comment]
And sometimes it runs it three times?!?

Changed end of Async.pm6 to this:
```
END {
    say "end";
    Log::Async.instance.done;
}
```

Then ran it like this:
```
$ cat A.pm6 
use Log::Async;
$ cat B.pm6 
use Log::Async;
{master} ~/git/p6-log-async/t$ cat test-done.t 
use A;
use B;

say "in main";
$ perl6 -I. test-done.t 
end
end
in main
end
===SORRY!===
No such method 'done' for invocant of type 'Any'
```

So it printed "end" three times?

**Comment by CurtTilmes** [comment]
Ok, I see.  It runs the END once when it compiles A.pm6, once when it compiles B.pm6, and once when it compiles the main program.  If I run it again, A and B are already pre-compiled, so it only prints end once.

I think..

(But I still get the SORRY.)

**Comment by CurtTilmes** [comment]
I added a ```say "export";``` to the beginning of sub EXPORT, and reran test-done.t from above twice:

First execution (where it compiles A and B):
```
export
end
export
end
in main
end
===SORRY!===
No such method 'done' for invocant of type 'Any'
```

Second execution, using precompiled:
```
in main
end
===SORRY!===
No such method 'done' for invocant of type 'Any'
```

Since the main program doesn't use Log::Async, the EXPORT() which runs only on compile never
runs to create the first logger.

The END() then runs, which can't .done it.

Create initial logger should probably be INIT()

**Comment by bduggan** [comment]
Fixed.
